artifact_uri: file:///Users/kennethmwandingi/ems/mlflow_runs/776354157073111220/abe477bea6f24de7addbaaed604a1119/artifacts
end_time: 1749372044522
entry_point_name: ''
experiment_id: '776354157073111220'
lifecycle_stage: active
run_id: abe477bea6f24de7addbaaed604a1119
run_name: learning_DE_KN_residential1_phases_20250608_1040
run_uuid: abe477bea6f24de7addbaaed604a1119
source_name: ''
source_type: 4
source_version: ''
start_time: 1749372044271
status: 3
tags: []
user_id: kennethmwandingi
