[theme]
# Palette colors: "#00838f", "#f4a98a", "#88233e", "#142b42", "#0e6072"

# Main accent color for interactive elements
primaryColor = "#00838f"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text
textColor = "#142b42"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
font = "sans serif"
